### ISSUE TITLE
Publish Package on NPM

### ISSUE THREAD

**Issue by rafaelmaeuer** [swrlab/node-utils#425]
Currently this package is published as [node-storage-wrapper](https://github.com/swrlab/node-utils/packages/327932) which should get a deprecation note.
The new version - which is currently only available as link-dependency with beta-flag - should be published on NPM as `@swrlab/utils` or `@swrlab/node-utils`.

**Comment by frytg** [comment]
`@swrlab/node-storage-wrapper` is now marked as deprecated https://www.npmjs.com/package/@swrlab/node-storage-wrapper

**Comment by rafaelmaeuer** [comment]
Solved with https://www.npmjs.com/package/@swrlab/utils
