### ISSUE TITLE
Please provide TypeScript definition

### ISSUE THREAD

**Issue by staticfinal** [swrlab/node-utils#458]
It would be nice to have TypeScript definitions for the functions provided in `packages`.

**Comment by rafaelmaeuer** [comment]
Hey and thanks for the proposal, this is currently out of our scope, but feel free to submit a PR!

**Comment by rafaelmaeuer** [comment]
Leaving those links here as the transition to typescript should also include compatibility-layers for CJS and ESM:
- [How to Create a Hybrid NPM Module for ESM and CommonJS](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html)
- [Ship ESM & CJS in one Package](https://antfu.me/posts/publish-esm-and-cjs)
