### ISSUE TITLE
Improvements for next release

### ISSUE THREAD

**Issue by rafaelmaeuer** [swrlab/node-utils#466]
Some ideas for improvements in next release:

- [ ] ~~migrate radioCategories from app-analytics-board~~
- [ ] ~~migrate regionCodes from app-analytics-board~~

**Comment by frytg** [comment]
- [ ] add tool to format numbers in readable format: 1234567 -> 1.234.567
- [ ] add sleeper tool (`await sleep(1e3)`)

```js
const sleep = (ms) => {
	return new Promise((resolve) => {
		setTimeout(resolve, ms)
	})
}
```

**Comment by rafaelmaeuer** [comment]
Some further candidates found in app-analytics/utils and swr2-app/utils:
- [ ] capitalize: word --> Word
```js
word[0].toUpperCase() + word.slice(1)
```
- [ ] pluralize: (count
```js
(count, singular, plural) => `${count} ${count !== 1 ? plural : singular}`
```

**Comment by rafaelmaeuer** [comment]
> 

should these also be part of strings helper package or should we define a new one? E.g. one package for `numbers`, could include additional math helpers, another package could be something like `functions` or similar.

**Comment by rafaelmaeuer** [comment]
[Using Reduce to Count the Array in Javascript](https://helloacm.com/using-reduce-to-count-the-array-in-javascript/)

```js
function reduceArrayToObjectCount(array) {
	return array.reduce((obj, name) => {
		// eslint-disable-next-line no-plusplus
		obj[name] = obj[name] ? ++obj[name] : 1
		return obj
	}, {})
}
```

**Comment by rafaelmaeuer** [comment]
Improve Numbers/Math helpers:
- [ ] round(value, precision)
- [ ] random(min, max)
