### ISSUE TITLE
Refactor Storage-wrapper

### ISSUE THREAD

**Issue by rafaelmaeuer** [swrlab/node-utils#528]
To conform our current package structure following suggestions:

- [x] move function files from `packages/storage-wrapper` to `utils/storage`
- [x] rename `packages/storage-wrapper` to `storage`
- [ ] adapt export scheme from `packages/index.js` to other packages
  - instead of exporting class with this.function, export object with functions

**Comment by frytg** [comment]
Also noticed some logs about an upcoming change, could be worth migrating the AWS SDK as well https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html (see radiohub-ingest, which already uses the new util)

```
Please migrate your code to use AWS SDK for JavaScript (v3).
(node:29) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
For more information, check the migration guide at https://a.co/7PzMCcy
```

**Comment by frytg** [comment]
Note to self: 

- [ ] Test new branch in Radiohub API
- [ ] add `customGetSignedUrl` for AWS links
- [ ] add S3 to testing
- [ ] add keys to GitHub Actions
